import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783204790489 implements MigrationInterface {
    name = 'InitialSchema1783204790489'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_STATUS_CHANGED', 'TASK_COMMENT_ADDED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'MEETING_INVITATION', 'MEETING_UPDATED', 'MEETING_CANCELLED', 'MEETING_REMINDER', 'MEETING_STARTING_SOON', 'MEETING_RESPONSE_NEEDED', 'ROLE_ASSIGNED', 'ACCOUNT_UPDATED', 'DAILY_DIGEST', 'WEEKLY_DIGEST')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('EMAIL', 'IN_APP', 'PUSH')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'READ', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'PENDING', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'MEDIUM', "title" character varying NOT NULL, "message" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "actionButtons" jsonb, "groupKey" character varying, "readAt" TIMESTAMP, "sentAt" TIMESTAMP, "failureReason" character varying, "retryCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a4bcfe446386dfd2319ca352d" ON "notifications" ("groupKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_2306bdfb5ae9f629eea0a28e4e" ON "notifications" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace6f52798f2c37bdd969a1fa7" ON "notifications" ("tenant_id", "userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d93ddd7e1b890535ecafbb334e" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_STATUS_CHANGED', 'TASK_COMMENT_ADDED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'MEETING_INVITATION', 'MEETING_UPDATED', 'MEETING_CANCELLED', 'MEETING_REMINDER', 'MEETING_STARTING_SOON', 'MEETING_RESPONSE_NEEDED', 'ROLE_ASSIGNED', 'ACCOUNT_UPDATED', 'DAILY_DIGEST', 'WEEKLY_DIGEST')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_channel_enum" AS ENUM('EMAIL', 'IN_APP', 'PUSH')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL, "type" "public"."notification_templates_type_enum" NOT NULL, "channel" "public"."notification_templates_channel_enum" NOT NULL, "subject" character varying, "bodyTemplate" text NOT NULL, "actionButtonsTemplate" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f4735819bdfeab818905410129" UNIQUE ("type", "channel"), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_notificationtype_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_STATUS_CHANGED', 'TASK_COMMENT_ADDED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'MEETING_INVITATION', 'MEETING_UPDATED', 'MEETING_CANCELLED', 'MEETING_REMINDER', 'MEETING_STARTING_SOON', 'MEETING_RESPONSE_NEEDED', 'ROLE_ASSIGNED', 'ACCOUNT_UPDATED', 'DAILY_DIGEST', 'WEEKLY_DIGEST')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_digestfrequency_enum" AS ENUM('DISABLED', 'DAILY', 'WEEKLY')`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "userId" uuid NOT NULL, "notificationType" "public"."notification_preferences_notificationtype_enum" NOT NULL, "channelPreferences" jsonb NOT NULL, "digestFrequency" "public"."notification_preferences_digestfrequency_enum" NOT NULL DEFAULT 'DISABLED', "doNotDisturb" jsonb NOT NULL DEFAULT '{"enabled":false,"startTime":"22:00","endTime":"09:00"}', "bypassDndForCritical" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3c15d28f23c3a3a6813424e1ad8" UNIQUE ("tenant_id", "userId", "notificationType"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1860f9fce126ae48cbfeac30c" ON "notification_preferences" ("tenant_id", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e907e614e2cc6216ac076eb75e" ON "notification_preferences" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" character varying NOT NULL, "tenant_id" uuid, "task_id" character varying NOT NULL, "user_id" character varying NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bae41308a2185399e6bec738b5" ON "comments" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_action_enum" AS ENUM('CREATED', 'STATUS_UPDATED', 'ASSIGNED', 'VISIBILITY_UPDATED', 'UPDATED', 'DELETED', 'COMMENT_ADDED', 'SUBTASK_ADDED', 'SUBTASK_UPDATED', 'TAG_ADDED', 'TAG_REMOVED', 'ATTACHMENT_ADDED', 'MENTOR_ASSIGNED', 'HELP_REQUESTED', 'HANDOVER_REQUESTED', 'TASK_VOLUNTEERED')`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" character varying NOT NULL, "tenant_id" uuid, "task_id" character varying NOT NULL, "user_id" character varying NOT NULL, "action" "public"."activity_logs_action_enum" NOT NULL, "details" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a31d59aa71dfdbfa616615863" ON "activity_logs" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."subtasks_status_enum" AS ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "subtasks" ("id" character varying NOT NULL, "tenant_id" uuid, "parent_id" character varying NOT NULL, "title" character varying(200) NOT NULL, "status" "public"."subtasks_status_enum" NOT NULL DEFAULT 'TODO', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_035c1c153f0239ecc95be448d96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54034d0de00c95823883346d57" ON "subtasks" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" character varying NOT NULL, "tenant_id" uuid, "name" character varying(50) NOT NULL, "color" character varying(7), "club_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad59358c67a937c8a8e785804c" ON "tags" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELED')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_visibility_enum" AS ENUM('PRIVATE', 'PUBLIC')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" character varying NOT NULL, "tenant_id" uuid, "title" character varying(200) NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'TODO', "visibility" "public"."tasks_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "assigner_id" character varying NOT NULL, "assignee_id" character varying, "due_date" TIMESTAMP, "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "estimated_time" integer, "points" integer, "is_recurring" boolean NOT NULL DEFAULT false, "recurring_schedule" character varying, "required_skills" text, "mentor_id" character varying, "club_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_49c6d908126bd669cde89171bf" ON "tasks" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_eab180ee72c57d6eef524370f5" ON "tasks" ("tenant_id", "club_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_93edccfc42408754c4b5957105" ON "tasks" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("id" character varying NOT NULL, "task_id" character varying NOT NULL, "depends_on_task_id" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e31de0e173af595a21c4ec8e48b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_34abffd156d4d10466f5f254ef" ON "task_dependencies" ("task_id", "depends_on_task_id") `);
        await queryRunner.query(`CREATE TYPE "public"."club_roles_roletype_enum" AS ENUM('LEADER', 'MEMBER', 'MODERATOR', 'CUSTOM')`);
        await queryRunner.query(`CREATE TABLE "club_roles" ("id" uuid NOT NULL, "clubId" uuid NOT NULL, "name" character varying(100) NOT NULL, "roleType" "public"."club_roles_roletype_enum" NOT NULL DEFAULT 'MEMBER', "permissions" text array NOT NULL DEFAULT ARRAY[]::text[], "isCustom" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_abe53d1672ba9a4132f11959502" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."club_announcements_scope_enum" AS ENUM('CLUB_ONLY', 'PUBLIC')`);
        await queryRunner.query(`CREATE TABLE "club_announcements" ("id" uuid NOT NULL, "clubId" uuid NOT NULL, "authorId" uuid NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "scope" "public"."club_announcements_scope_enum" NOT NULL DEFAULT 'CLUB_ONLY', "isPinned" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8722e4a31136a2edeb44aa43e21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clubs_visibility_enum" AS ENUM('PUBLIC', 'PRIVATE')`);
        await queryRunner.query(`CREATE TABLE "clubs" ("id" uuid NOT NULL, "tenantId" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(500) NOT NULL, "logoUrl" character varying, "visibility" "public"."clubs_visibility_enum" NOT NULL DEFAULT 'PUBLIC', "leaders" text array NOT NULL DEFAULT ARRAY[]::text[], "manifesto" text, "slackUrl" character varying, "discordUrl" character varying, "darkThemeEnabled" boolean NOT NULL DEFAULT false, "totalTasksCompleted" integer NOT NULL DEFAULT '0', "totalMeetingsHeld" integer NOT NULL DEFAULT '0', "createdByUserId" uuid NOT NULL, "tenantApiKey" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "tier" character varying(50) NOT NULL DEFAULT 'free', "maxMembers" integer NOT NULL DEFAULT '50', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b903a61ba85fad52421c4d077d9" UNIQUE ("tenantId"), CONSTRAINT "PK_bb09bd0c8d5238aeaa8f86ee0d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_416478623b6d04945a7fd054ca" ON "clubs" ("tenantApiKey") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b903a61ba85fad52421c4d077d" ON "clubs" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."club_members_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "club_members" ("id" uuid NOT NULL, "tenant_id" uuid, "clubId" uuid NOT NULL, "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "status" "public"."club_members_status_enum" NOT NULL DEFAULT 'PENDING', "joinedAt" TIMESTAMP, "appliedAt" TIMESTAMP, "approvedAt" TIMESTAMP, "approvedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_275708171b46ed0928fc40c38c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05f6b1df9b19a18f81458fadb6" ON "club_members" ("tenant_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4c2bce54e3b2d508f88af769ee" ON "club_members" ("clubId", "userId") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" character varying NOT NULL, "task_id" character varying NOT NULL, "uploaded_by" character varying NOT NULL, "file_name" character varying(255) NOT NULL, "file_url" text NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assignment_history" ("id" character varying NOT NULL, "task_id" character varying NOT NULL, "assigned_by" character varying NOT NULL, "assigned_to" character varying, "previous_assignee" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e3ec8e134976ba55ea4043b7bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."badges_type_enum" AS ENUM('TASK_COMPLETED', 'FIRST_TASK', 'TASKS_STREAK', 'MENTOR', 'HELPER', 'QUICK_RESPONDER', 'HIGH_QUALITY', 'COMMUNITY_CONTRIBUTOR')`);
        await queryRunner.query(`CREATE TABLE "badges" ("id" character varying NOT NULL, "tenant_id" uuid, "club_id" uuid, "user_id" character varying NOT NULL, "type" "public"."badges_type_enum" NOT NULL, "name" character varying(100) NOT NULL, "description" text NOT NULL, "points" integer NOT NULL, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d9c4ffa5d58780ff3a2f1ea389" ON "badges" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_feed_items_activitytype_enum" AS ENUM('TASK_COMPLETED', 'TASK_CREATED', 'CLUB_MEMBER_JOINED', 'MEETING_SCHEDULED', 'MEETING_CANCELLED', 'USER_JOINED', 'SOCIAL_POST_CREATED', 'SOCIAL_POST_LIKED', 'SOCIAL_COMMENT_ADDED')`);
        await queryRunner.query(`CREATE TABLE "activity_feed_items" ("id" character varying NOT NULL, "tenant_id" uuid NOT NULL, "userId" character varying NOT NULL, "activityType" "public"."activity_feed_items_activitytype_enum" NOT NULL, "metadata" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e375b6cdc882bae9574b895ff4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e4ff06a43086d7a3e42b6f851" ON "activity_feed_items" ("tenant_id", "activityType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d13a6dc86c73be49cfd56eb9f" ON "activity_feed_items" ("tenant_id", "userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1039d23e5040ffd1ac8fca7fc4" ON "activity_feed_items" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."communities_visibility_enum" AS ENUM('PUBLIC', 'PRIVATE', 'RESTRICTED')`);
        await queryRunner.query(`CREATE TABLE "communities" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(1000) NOT NULL, "visibility" "public"."communities_visibility_enum" NOT NULL DEFAULT 'PUBLIC', "founderId" uuid NOT NULL, "logoUrl" character varying, "websiteUrl" character varying, "tenantId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fea1fe83c86ccde9d0a089e7ea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed4bddbf66b74e31e28c425988" ON "communities" ("founderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_850429b73a8409269d7092f476" ON "communities" ("visibility") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8cd37dd1760222b2499c01e9d0" ON "communities" ("tenantId") WHERE "tenantId" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."community_members_status_enum" AS ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "community_members" ("id" uuid NOT NULL, "communityId" uuid NOT NULL, "userId" uuid NOT NULL, "status" "public"."community_members_status_enum" NOT NULL DEFAULT 'PENDING', "appliedAt" TIMESTAMP NOT NULL, "approvedAt" TIMESTAMP, "approvedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03dff82f9cfcb02498e9f5fc640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f331522d9362b87fc86b19b92a" ON "community_members" ("appliedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d2743f07f456813a1438db872" ON "community_members" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c7513dc4939c966a2350e50d0" ON "community_members" ("communityId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."meeting_participants_status_enum" AS ENUM('invited', 'accepted', 'declined', 'attending')`);
        await queryRunner.query(`CREATE TABLE "meeting_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "meeting_id" character varying NOT NULL, "user_id" character varying NOT NULL, "status" "public"."meeting_participants_status_enum" NOT NULL DEFAULT 'invited', "joined_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_994ee66a92de655fb478c038980" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17e48f01284624631900c5e977" ON "meeting_participants" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."meetings_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."meetings_location_type_enum" AS ENUM('physical', 'online')`);
        await queryRunner.query(`CREATE TYPE "public"."meetings_privacy_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TABLE "meetings" ("id" character varying NOT NULL, "tenant_id" uuid, "title" character varying(200) NOT NULL, "description" text, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP, "duration_minutes" integer NOT NULL, "organizer_id" character varying NOT NULL, "status" "public"."meetings_status_enum" NOT NULL DEFAULT 'scheduled', "meeting_url" character varying, "location" text, "location_type" "public"."meetings_location_type_enum" NOT NULL DEFAULT 'online', "privacy" "public"."meetings_privacy_enum" NOT NULL DEFAULT 'public', "recurrence_rule" text, "feedback_form_url" text, "club_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa73be861afa77eb4ed31f3ed57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22ae2e910f10944bc5c3be0cc1" ON "meetings" ("tenant_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_72e555a85991e167fcfb8bd9bc" ON "meetings" ("tenant_id", "club_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0560f34915cb12c3f22213c02e" ON "meetings" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_reason_enum" AS ENUM('HARASSMENT', 'HATE_SPEECH', 'SPAM', 'MISINFORMATION', 'INAPPROPRIATE_CONTENT', 'COPYRIGHT', 'VIOLENCE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', 'ESCALATED')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" character varying NOT NULL, "tenant_id" uuid NOT NULL, "reporterId" character varying NOT NULL, "targetUserId" character varying, "targetContentId" character varying, "reason" "public"."reports_reason_enum" NOT NULL, "description" text NOT NULL, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'OPEN', "moderatorId" character varying, "resolutionNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c1877004f107f46435a79ade7" ON "reports" ("tenant_id", "targetContentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6688cd2f587869c4d5d9648337" ON "reports" ("tenant_id", "targetUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_552cc95048deea3b449e687625" ON "reports" ("tenant_id", "status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_31b93a8f8e514c1633206fdd33" ON "reports" ("tenant_id", "reporterId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7272911ff87dc7a7a01ac32be" ON "reports" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."user_bans_action_enum" AS ENUM('WARN', 'HIDE_CONTENT', 'DELETE_CONTENT', 'SUSPEND_USER', 'BAN_USER_PERMANENT', 'BAN_USER_TEMPORARY', 'RESTORE_CONTENT')`);
        await queryRunner.query(`CREATE TABLE "user_bans" ("id" character varying NOT NULL, "tenant_id" uuid NOT NULL, "userId" character varying NOT NULL, "action" "public"."user_bans_action_enum" NOT NULL, "reason" text NOT NULL, "moderatorId" character varying NOT NULL, "banUntil" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_299b3ce7e72a9ac9aec5edeaf81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f67dd19d36c00b38e59a332b8" ON "user_bans" ("tenant_id", "userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c56dccec7aacaa97fb682c276e" ON "user_bans" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."meeting_resources_type_enum" AS ENUM('link', 'document', 'presentation', 'wiki', 'other')`);
        await queryRunner.query(`CREATE TABLE "meeting_resources" ("id" character varying NOT NULL, "meeting_id" character varying NOT NULL, "title" character varying(200) NOT NULL, "url" text NOT NULL, "type" "public"."meeting_resources_type_enum" NOT NULL DEFAULT 'link', "description" text, "uploaded_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cffbee718f6d713a3b1ab7663cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" character varying NOT NULL, "meeting_id" character varying NOT NULL, "user_id" character varying NOT NULL, "attended" boolean NOT NULL DEFAULT false, "joined_at" TIMESTAMP, "left_at" TIMESTAMP, "duration_minutes" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_216841907ac4ef990c19bab1377" UNIQUE ("meeting_id", "user_id"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "meeting_notes" ("id" character varying NOT NULL, "meeting_id" character varying NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "note_type" character varying(20) NOT NULL, "created_by" character varying NOT NULL, "is_converted_to_task" boolean NOT NULL DEFAULT false, "task_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24248684e8ac266a4bc2ba64475" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agenda_items" ("id" character varying NOT NULL, "meeting_id" character varying NOT NULL, "title" character varying(200) NOT NULL, "description" text, "duration" integer, "order" integer NOT NULL, "presenter_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7274c40301175b4b4b347820d0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL, "google_id" character varying NOT NULL, "email" character varying NOT NULL, "display_name" character varying NOT NULL, "avatar_url" character varying, "bio" text, "roles" text NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "global_role" character varying(50) NOT NULL DEFAULT 'ADMIN', "primary_tenant_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b" UNIQUE ("google_id"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a937934a959994405c1fd89937" ON "users" ("primary_tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_597fe5484dfc718873e29cf4cd" ON "users" ("global_role") `);
        await queryRunner.query(`CREATE TYPE "public"."api_keys_rate_limit_tier_enum" AS ENUM('FREE', 'PREMIUM', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TYPE "public"."api_keys_status_enum" AS ENUM('ACTIVE', 'REVOKED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL, "name" character varying NOT NULL, "key" character varying NOT NULL, "secret_hash" character varying NOT NULL, "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "scopes" jsonb NOT NULL DEFAULT '[]', "rate_limit_tier" "public"."api_keys_rate_limit_tier_enum" NOT NULL DEFAULT 'FREE', "expires_at" TIMESTAMP, "last_used_at" TIMESTAMP, "status" "public"."api_keys_status_enum" NOT NULL DEFAULT 'ACTIVE', "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e42cf55faeafdcce01a82d24849" UNIQUE ("key"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d243fa737f206a31ff6e342ef5" ON "api_keys" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ac18429c8d27858d79432e0dd" ON "api_keys" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3baee01d8408cd3c0f89a9a97" ON "api_keys" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e42cf55faeafdcce01a82d2484" ON "api_keys" ("key") `);
        await queryRunner.query(`CREATE TABLE "api_key_usage_logs" ("id" uuid NOT NULL, "api_key_id" uuid NOT NULL, "endpoint" character varying NOT NULL, "method" character varying NOT NULL, "status_code" integer NOT NULL, "ip_address" character varying, "user_agent" text, "response_time_ms" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_230073a0d5d421aefe8576a18d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f497943b598bb406ed9df3fc2e" ON "api_key_usage_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a64b7ac44d55d6e48b2b3cf3fd" ON "api_key_usage_logs" ("api_key_id") `);
        await queryRunner.query(`CREATE TYPE "public"."rsvp_responses_status_enum" AS ENUM('going', 'not_going', 'maybe', 'no_response')`);
        await queryRunner.query(`CREATE TABLE "rsvp_responses" ("id" character varying NOT NULL, "meeting_id" character varying NOT NULL, "user_id" character varying NOT NULL, "status" "public"."rsvp_responses_status_enum" NOT NULL DEFAULT 'no_response', "responded_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7103e099d1d378636f2c710e2d8" UNIQUE ("meeting_id", "user_id"), CONSTRAINT "PK_5885079f35d42286e41184db73b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_roletype_enum" AS ENUM('ADMIN', 'MODERATOR', 'VOLUNTEER', 'MEMBER', 'GUEST')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" character varying NOT NULL, "roleType" "public"."roles_roletype_enum" NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "permissions" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f9f0a2c0ac4b6c658aecf75796a" UNIQUE ("roleType"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."social_posts_status_enum" AS ENUM('PUBLISHED', 'HIDDEN', 'DELETED', 'FLAGGED')`);
        await queryRunner.query(`CREATE TABLE "social_posts" ("id" character varying NOT NULL, "tenant_id" uuid, "authorId" character varying NOT NULL, "content" text NOT NULL, "imageUrls" text array, "likesCount" integer NOT NULL DEFAULT '0', "likedBy" text array NOT NULL DEFAULT '{}', "commentsCount" integer NOT NULL DEFAULT '0', "status" "public"."social_posts_status_enum" NOT NULL DEFAULT 'PUBLISHED', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2161864ea79f14525b8804bd7ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8508e10367ba4ed15de8d16405" ON "social_posts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b3e02f91b9691ca1b3714ec6a" ON "social_posts" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2907647bd015897967cdd6efed" ON "social_posts" ("authorId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "task_tags" ("task_id" character varying NOT NULL, "tag_id" character varying NOT NULL, CONSTRAINT "PK_a7354e3c3f630636f6e4a29694a" PRIMARY KEY ("task_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70515bc464901781ac60b82a1e" ON "task_tags" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f883135d033e1541f6a81972e7" ON "task_tags" ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_300e98d0bf7b02d33e952ad0508" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtasks" ADD CONSTRAINT "FK_b3e0fc1e130a765a5fe9a4da2d4" FOREIGN KEY ("parent_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_26dedda08faccdb95aff99e112e" FOREIGN KEY ("depends_on_task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_roles" ADD CONSTRAINT "FK_2621fd6f34351fdecb6ead2efa4" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_announcements" ADD CONSTRAINT "FK_4623dbd5d1d23a4d6b51b547db0" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_members" ADD CONSTRAINT "FK_78ff67cd114294877e6b173ac13" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_members" ADD CONSTRAINT "FK_4e59f2d11c6ee5fb5486482b8f7" FOREIGN KEY ("roleId") REFERENCES "club_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e62fd181b97caa6b150b09220b1" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_history" ADD CONSTRAINT "FK_cc06f927b425fe71c3dcccef7dc" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_members" ADD CONSTRAINT "FK_692f4422c79d6efe4f2cfbe6063" FOREIGN KEY ("communityId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_participants" ADD CONSTRAINT "FK_4d2e803caeb25541cc89f2efa5b" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_resources" ADD CONSTRAINT "FK_0c1d5fcf7d8aa0458e12daad1fa" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_a3ca60d8ae64244789c0343092f" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_notes" ADD CONSTRAINT "FK_2447d9d3ce92c6e8f5a2d391202" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_items" ADD CONSTRAINT "FK_c58f166b8bff4fd19c5353cd310" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key_usage_logs" ADD CONSTRAINT "FK_a64b7ac44d55d6e48b2b3cf3fdb" FOREIGN KEY ("api_key_id") REFERENCES "api_keys"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rsvp_responses" ADD CONSTRAINT "FK_db7e209e79dd25d47416ccd1ff8" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_70515bc464901781ac60b82a1ea" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_f883135d033e1541f6a81972e7d" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_f883135d033e1541f6a81972e7d"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_70515bc464901781ac60b82a1ea"`);
        await queryRunner.query(`ALTER TABLE "rsvp_responses" DROP CONSTRAINT "FK_db7e209e79dd25d47416ccd1ff8"`);
        await queryRunner.query(`ALTER TABLE "api_key_usage_logs" DROP CONSTRAINT "FK_a64b7ac44d55d6e48b2b3cf3fdb"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973"`);
        await queryRunner.query(`ALTER TABLE "agenda_items" DROP CONSTRAINT "FK_c58f166b8bff4fd19c5353cd310"`);
        await queryRunner.query(`ALTER TABLE "meeting_notes" DROP CONSTRAINT "FK_2447d9d3ce92c6e8f5a2d391202"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_a3ca60d8ae64244789c0343092f"`);
        await queryRunner.query(`ALTER TABLE "meeting_resources" DROP CONSTRAINT "FK_0c1d5fcf7d8aa0458e12daad1fa"`);
        await queryRunner.query(`ALTER TABLE "meeting_participants" DROP CONSTRAINT "FK_4d2e803caeb25541cc89f2efa5b"`);
        await queryRunner.query(`ALTER TABLE "community_members" DROP CONSTRAINT "FK_692f4422c79d6efe4f2cfbe6063"`);
        await queryRunner.query(`ALTER TABLE "assignment_history" DROP CONSTRAINT "FK_cc06f927b425fe71c3dcccef7dc"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e62fd181b97caa6b150b09220b1"`);
        await queryRunner.query(`ALTER TABLE "club_members" DROP CONSTRAINT "FK_4e59f2d11c6ee5fb5486482b8f7"`);
        await queryRunner.query(`ALTER TABLE "club_members" DROP CONSTRAINT "FK_78ff67cd114294877e6b173ac13"`);
        await queryRunner.query(`ALTER TABLE "club_announcements" DROP CONSTRAINT "FK_4623dbd5d1d23a4d6b51b547db0"`);
        await queryRunner.query(`ALTER TABLE "club_roles" DROP CONSTRAINT "FK_2621fd6f34351fdecb6ead2efa4"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_26dedda08faccdb95aff99e112e"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707"`);
        await queryRunner.query(`ALTER TABLE "subtasks" DROP CONSTRAINT "FK_b3e0fc1e130a765a5fe9a4da2d4"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_300e98d0bf7b02d33e952ad0508"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f883135d033e1541f6a81972e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70515bc464901781ac60b82a1e"`);
        await queryRunner.query(`DROP TABLE "task_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2907647bd015897967cdd6efed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b3e02f91b9691ca1b3714ec6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8508e10367ba4ed15de8d16405"`);
        await queryRunner.query(`DROP TABLE "social_posts"`);
        await queryRunner.query(`DROP TYPE "public"."social_posts_status_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_roletype_enum"`);
        await queryRunner.query(`DROP TABLE "rsvp_responses"`);
        await queryRunner.query(`DROP TYPE "public"."rsvp_responses_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a64b7ac44d55d6e48b2b3cf3fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f497943b598bb406ed9df3fc2e"`);
        await queryRunner.query(`DROP TABLE "api_key_usage_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e42cf55faeafdcce01a82d2484"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3baee01d8408cd3c0f89a9a97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ac18429c8d27858d79432e0dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d243fa737f206a31ff6e342ef5"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP TYPE "public"."api_keys_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."api_keys_rate_limit_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_597fe5484dfc718873e29cf4cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a937934a959994405c1fd89937"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "agenda_items"`);
        await queryRunner.query(`DROP TABLE "meeting_notes"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TABLE "meeting_resources"`);
        await queryRunner.query(`DROP TYPE "public"."meeting_resources_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c56dccec7aacaa97fb682c276e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f67dd19d36c00b38e59a332b8"`);
        await queryRunner.query(`DROP TABLE "user_bans"`);
        await queryRunner.query(`DROP TYPE "public"."user_bans_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7272911ff87dc7a7a01ac32be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31b93a8f8e514c1633206fdd33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_552cc95048deea3b449e687625"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6688cd2f587869c4d5d9648337"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1877004f107f46435a79ade7"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0560f34915cb12c3f22213c02e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72e555a85991e167fcfb8bd9bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22ae2e910f10944bc5c3be0cc1"`);
        await queryRunner.query(`DROP TABLE "meetings"`);
        await queryRunner.query(`DROP TYPE "public"."meetings_privacy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."meetings_location_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."meetings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17e48f01284624631900c5e977"`);
        await queryRunner.query(`DROP TABLE "meeting_participants"`);
        await queryRunner.query(`DROP TYPE "public"."meeting_participants_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c7513dc4939c966a2350e50d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d2743f07f456813a1438db872"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f331522d9362b87fc86b19b92a"`);
        await queryRunner.query(`DROP TABLE "community_members"`);
        await queryRunner.query(`DROP TYPE "public"."community_members_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cd37dd1760222b2499c01e9d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_850429b73a8409269d7092f476"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed4bddbf66b74e31e28c425988"`);
        await queryRunner.query(`DROP TABLE "communities"`);
        await queryRunner.query(`DROP TYPE "public"."communities_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1039d23e5040ffd1ac8fca7fc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d13a6dc86c73be49cfd56eb9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e4ff06a43086d7a3e42b6f851"`);
        await queryRunner.query(`DROP TABLE "activity_feed_items"`);
        await queryRunner.query(`DROP TYPE "public"."activity_feed_items_activitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9c4ffa5d58780ff3a2f1ea389"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP TYPE "public"."badges_type_enum"`);
        await queryRunner.query(`DROP TABLE "assignment_history"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2bce54e3b2d508f88af769ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05f6b1df9b19a18f81458fadb6"`);
        await queryRunner.query(`DROP TABLE "club_members"`);
        await queryRunner.query(`DROP TYPE "public"."club_members_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b903a61ba85fad52421c4d077d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_416478623b6d04945a7fd054ca"`);
        await queryRunner.query(`DROP TABLE "clubs"`);
        await queryRunner.query(`DROP TYPE "public"."clubs_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "club_announcements"`);
        await queryRunner.query(`DROP TYPE "public"."club_announcements_scope_enum"`);
        await queryRunner.query(`DROP TABLE "club_roles"`);
        await queryRunner.query(`DROP TYPE "public"."club_roles_roletype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34abffd156d4d10466f5f254ef"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93edccfc42408754c4b5957105"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eab180ee72c57d6eef524370f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c6d908126bd669cde89171bf"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad59358c67a937c8a8e785804c"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54034d0de00c95823883346d57"`);
        await queryRunner.query(`DROP TABLE "subtasks"`);
        await queryRunner.query(`DROP TYPE "public"."subtasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a31d59aa71dfdbfa616615863"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bae41308a2185399e6bec738b5"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e907e614e2cc6216ac076eb75e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1860f9fce126ae48cbfeac30c"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_digestfrequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_notificationtype_enum"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93ddd7e1b890535ecafbb334e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace6f52798f2c37bdd969a1fa7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2306bdfb5ae9f629eea0a28e4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a4bcfe446386dfd2319ca352d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
    }

}
